### ISSUE TITLE
Can't add/update large script in supporting objects

### ISSUE THREAD

**Issue by tschf** [OraOpenSource/OXAR#135]
Was just going to upload a script through the script editor (same applies to modify an existing if I previously uploaded from file upload) and when hitting Apply changes, get a 'site cannot be reached' error page:

![image](https://cloud.githubusercontent.com/assets/1747643/13552133/8773af8c-e3a8-11e5-8050-9dcf517e8c6d.png)

![image](https://cloud.githubusercontent.com/assets/1747643/13552140/e49ca01a-e3a8-11e5-9a58-3e16cf173326.png)

The script file size is 2.5MB

edit - Even, I can't switch to script properties

**Comment by tschf** [comment]
Running through Tomcat, I receive a different error:

![image](https://cloud.githubusercontent.com/assets/1747643/13552167/d3ef6778-e3aa-11e5-8de4-9ca66677ac33.png)

**Comment by martindsouza** [comment]
@tschf I'd solve the problem from Tomcat first. N4O is just proxying to Tomcat.

Have you tried with the latest ORDS and 5.0.3 APEX?

**Comment by tschf** [comment]
Thanks @martindsouza. I'm up to date on APEX, but not on ORDS. Will update that first and report back.

**Comment by tschf** [comment]
Updated ORDS to latest with the same.
Also, just to add another error page to the mix, running in standalone mode:

![image](https://cloud.githubusercontent.com/assets/1747643/13568796/f91109f4-e4b7-11e5-98e9-ed15f6335f2c.png)

```
2016-03-07 02:52:53.701:WARN:oejs.ServletHandler:qtp244978591-17: /ords/wwv_flow.accept
java.lang.IllegalStateException: Form too large: 3217723 > 200000
	at org.eclipse.jetty.server.Request.extractFormParameters(Request.java:364)
	at org.eclipse.jetty.server.Request.extractContentParameters(Request.java:302)
	at org.eclipse.jetty.server.Request.extractParameters(Request.java:256)
	at org.eclipse.jetty.server.Request.getParameterMap(Request.java:841)
	at oracle.dbtools.http.servlet.NormalizedHttpServletRequest.formParameters(NormalizedHttpServletRequest.java:167)
	at oracle.dbtools.http.servlet.NormalizedHttpServletRequest.<init>(NormalizedHttpServletRequest.java:110)
	at oracle.dbtools.rt.web.HttpEndpointBase.service(HttpEndpointBase.java:65)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:751)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:566)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:219)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1111)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:498)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1045)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:199)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:98)
	at org.eclipse.jetty.server.Server.handle(Server.java:461)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:284)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:244)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:534)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:607)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:536)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by tschf** [comment]
Excluding the standalone mode, to resolve it on tomcat/n40, the tomcat configuration needs an update to the property maxPostSize, which has a limit of 2MB by default (if not specified).
