### ISSUE TITLE
Out of HeapM:q!

### ISSUE THREAD

**Issue by GasparYYC** [OraOpenSource/OXAR#174]

**Comment by GasparYYC** [comment]
Hi,
 Sharing with the team how to fix the Java heap space error.

One of my apps just started failing (no code/configuration changes whatsover).
The only change has been more data..

In my case in the file /usr/share/tomcat/logs/catalina.2016-08-29.log  
I received errors like this:

`Aug 29, 2016 6:56:58 PM oracle.dbtools.common.config.db.DatabasePools getPool
SEVERE: The pool named: apex is not correctly configured, error: Error during pool creation in Universal Connection Pool Manager: oracle.ucp.UniversalConnectionPoolException: Universal Connection Pool already exists in the Universal Connection Pool Manager. Universal Connection Pool cannot be added to the Universal Connection Pool Manager
oracle.dbtools.common.jdbc.ConnectionPoolException: The pool named: apex is not correctly configured, error: Error during pool creation in Universal Connection Pool Manager: oracle.ucp.UniversalConnectionPoolException: Universal Connection Pool already exists in the Universal Connection Pool Manager. Universal Connection Pool cannot be added to the Universal Connection Pool Manager
        at oracle.dbtools.common.jdbc.ConnectionPoolException.badConfiguration(ConnectionPoolException.java:88)
        at oracle.dbtools.common.config.db.DatabasePools.badConfiguration(DatabasePools.java:206)
.
.
.`

After some searching I found some inconsistent,obsolete and contradicting information on what file to edit to reconfigure the Java Heap..  I managed to figure out where to change it..  

In the file: 
/usr/share/tomcat/conf/tomcat.conf

Add the following line to configure 312MB of Memory to the Java Heap:
JAVA_OPTS="-Xmx312m"


Note:
I probably shrinked the java heap based on the memory usage before and after because after the change I actually have more memory available in the VM!

Before:
` free -m
              total        used        free      shared  buff/cache   available
Mem:            993         468          71         246         452         144
Swap:          4095         153        3942
`

After:
`#  free -m
              total        used        free      shared  buff/cache   available
Mem:            993         515         131         132         346         206
Swap:          4095         230        3865
`
(see 144 free of before vs. 206 of after)

My theory:
 My 1GB VM ran out of space when the heap tried to grow.. by defining a smaller Max Limit of the JVM heap I forced java to do a more thorough garbage collection hence behaving better..

So there you go.. just sharing..

I think it would be a good idea to add a "Troubleshooting and Best Practices" section for OXAR installations that could have information like this.

Regards

**Comment by martindsouza** [comment]
@GasparYYC thanks for the tip. Why the `312m` though? I.e. where is that number coming from?

**Comment by GasparYYC** [comment]
Hi,
 The value of 312 was somewhat arbitrary because initially Java was reporting 250 MB of MaxHeapSize used  (262144000 is in bytes):

/usr/bin/java  -XX:+PrintFlagsFinal -version |grep HeapSize
    uintx ErgoHeapSizeLimit                         = 0                                   {product}
    uintx HeapSizePerGCThread                       = 87241520                            {product}
    uintx InitialHeapSize                          := 16777216                            {product}
    uintx LargePageHeapSizeThreshold                = 134217728                           {product}
    uintx MaxHeapSize                              := 262144000                           {product}
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)


So initially I thought I was increasing it.. but turns out that the reporting of memory using the command above is possibly showing incorrect results for OpenJDK. When I checked the memory in the VM I saw that I actually reduced it.
The new value of 312MB on a VM with 1GB of RAM with OXAR seems to be working fine and is as fast as before.

If I had to recommend an initial value I would definitely go with 312MB. Seems to be a sweet spot.

-G
